POST http://localhost:8189/travel/api/v1/articles/likes
Content-Type: application/json

{
  "article": 2,
  "user": 1,
  "likeDislike": 11,
  "rating": 57
}

###
GET http://localhost:8189/travel/api/v1/articles/likes
Accept: application/json

###

DELETE http://localhost:8189/travel/api/v1/articles/likes/article_id=1/user_id=2
Accept: application/json

###

